### ISSUE TITLE
Request for new release with updated dependencies

### ISSUE THREAD

**Issue by Mikescops** [codebytere/node-mac-auth#18]
Hello,

Thanks for this project, would you be able to release a new version with the updated dependencies?

Thanks!

**Comment by Mikescops** [comment]
Hello,

Just an up on this 🚀 thanks!

**Comment by codebytere** [comment]
hey @Mikescops - sure, will do within the next day or two!

**Comment by Mikescops** [comment]
Thanks a lot 😄

**Comment by codebytere** [comment]
Done: https://www.npmjs.com/package/node-mac-auth/v/1.1.0
