### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by Mikescops** [codebytere/node-mac-auth#19]
Hello,

Can you add TypeScript typings and publish them to the npmjs repo?

Here are the typings:

```
declare module 'node-mac-auth' {
    export function promptTouchID(params: { reason: string; reuseDuration?: number }): Promise<void>;
    export function canPromptTouchID(): boolean;
}
```

**Comment by codebytere** [comment]
Done in 0d2c32e

**Comment by Mikescops** [comment]
@codebytere hey, thanks but they are missing in the final npmjs package, you should probably reference the types file in the package.json

**Comment by codebytere** [comment]
@codebytere yes, i committed this after the latest release - that's expected. I'll try to draft a new one.

**Comment by Mikescops** [comment]
@codebytere hey, just a reminder on this one, thanks 🙏
